- name: Banner | Install necessary packages for beautiful banner
  ansible.builtin.package:
    name:
      - figlet
      - toilet
    state: present

- name: Banner | Ensure /etc/update-motd.d directory exists
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Banner | Ensure /etc/profile.d/motd.sh directory exists for RedHat
  ansible.builtin.file:
    path: /etc/profile.d/motd.sh
    state: touch
    owner: root
    group: root
    mode: "0755"
  when: ansible_os_family | lower == 'redhat'

- name: Banner | Configure the motd.d file to 00-custom-header
  ansible.builtin.template:
    src: 00-custom-header.j2
    dest: /etc/update-motd.d/00-custom-header
    owner: root
    group: root
    mode: "0755"

- name: Banner | Configure the motd.d file 99-ansible-info
  ansible.builtin.template:
    src: "99-ansible-managed.j2"
    dest: "/etc/update-motd.d/99-ansible-info"
    owner: root
    group: root
    mode: "0755"

- name: Banner | Disable motd.d files to don't show them in banner
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: file
    owner: root
    group: root
    mode: "0644"
  ignore_errors: true
  with_items:
    - 00-header
    - 10-help-text
    - 50-landscape-sysinfo
    - 50-motd-news
    - 88-esm-announce
    - 91-release-upgrade
    - 98-reboot-required
  when: ansible_os_family | lower == 'debian'

- name: Banner | Ensure scripts on /etc/profile.d/motd.sh on RedHat
  ansible.builtin.lineinfile:
    path: /etc/profile.d/motd.sh
    line: "#!/bin/sh"
  when: ansible_os_family | lower == 'redhat'

- name: Banner | Ensure scripts on /etc/profile.d/motd.sh on RedHat
  ansible.builtin.blockinfile:
    path: /etc/profile.d/motd.sh
    block: |
      if [ -n "$SSH_CONNECTION" ]; then
        /etc/update-motd.d/00-custom-header
        /etc/update-motd.d/99-ansible-info
      fi
    state: present
  when: ansible_os_family | lower == 'redhat'
